# Site settings
title: David A Seeman
author: Dave
email: daveseeman12@gmail.com
description: Dave Seeman's blog
url: "http://daveas.me"
social_username:   daveaseeman
github_username:   daveas

# Build settings
markdown: kramdown
permalink: /:categories/:title
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
