# Site settings
title: Um, Dave?!
email: daveseeman12@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  <h3>Hi, I’m Dave Seeman.</h3>
  <p>I'm a Design Engineer living in Knoxville, TN with my wife, Kimberly (that's us below).
  Besides being an engineer, I am also a wannabe designer, marketer, and programmer.
  If anything, I just have too many interests.
  Most of these turn into projects because I have fun when I'm learning and making something new.</p>
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dseeman.github.io" # the base hostname & protocol for your site
twitter_username:   dave_seeman
github_username:    dseeman
linkedin_username:  daveseeman

# Build settings
markdown: kramdown

collections:
  projects:
  output: true
