# Site settings
title: Um, Dave?!
email: daveseeman12@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a Design Engineer living in Knoxville, TN with my wife.
  I like to write about productivity, learning, and creating products through design and engineering.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wlo.li" # the base hostname & protocol for your site
twitter_username:   dave_seeman
github_username:    dseeman
linkedin_username:  daveseeman

# Build settings
