# Site settings
title: Dave Seeman
email: daveseeman12@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Dave Seeman is a Design Engineer living in Knoxville, TN with his wife.
  He writes about productivity, learning, and creating things through engineering, design, and code.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://wlo.li" # the base hostname & protocol for your site
twitter_username: dave_seeman
github_username:  dseeman
linkedin_username: daveseeman

# Build settings
markdown: kramdown
