# Site Settings
title: David A Seeman
author: Dave Seeman
email: daveseeman12@gmail.com
description: Dave Seeman's blog
url: "http://daveas.me"
github: "http://daveas.github.io"
github_stl: "https://embed.github.com/view/3d/daveas/3D-Products/master/"
google_analytics: UA-51898808-6
long_name: daveaseeman
short_name: daveas

# Build Settings
permalink: /:categories/:title
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

gems:
  - jemoji
  - jekyll-sitemap
