# Site Settings
title: David A Seeman
author: Dave Seeman
email: daveseeman12@gmail.com
description: Dave Seeman's blog
url: "http://daveas.me"
github: "http://daveas.github.io"
google_analytics: UA-51898808-6
long_name: daveaseeman
short_name: daveas

# Build Settings
permalink: /posts/:path/
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
collections:
  projects:
    output: true
    permalink: /projects/:path/
gems:
  - jemoji
  - jekyll-sitemap
