# Site settings
title: Um, Dave?!
author: Dave Seeman
email: daveseeman12@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a Design Engineer living in Knoxville, TN with my beautiful wife and best friend, Kimberly.<br><br>
  When I'm not at work or spending quality time with my wife, I am probably having fun working on a side-project.
  If I'm programming it's probably in Ruby and if I'm using CAD it's definitely Onshape.
  Either way, I'm having fun when I'm learning and creating something new.
# baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dseeman.github.io" # the base hostname & protocol for your site
twitter_username:   dave_seeman
github_username:    dseeman
linkedin_username:  daveseeman

# Build settings
markdown: kramdown

collections:
  projects:
  output: true
