# Site Settings
title: Dave A Seeman
author: Dave
email: daveseeman12@gmail.com
description: The projects and writing of maker, designer, and engineer, Dave A Seeman.
url: "http://daveaseeman.com"
icon: /assets/images/icon.png
github: "http://daveaseeman.github.io"
google_analytics: UA-51898808-6
handle: daveaseeman
images: /assets/images/
docs: /assets/docs/

# Build Settings
markdown: kramdown
permalink: /posts/:title/
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
collections:
  projects:
    output: true
    permalink: /projects/:path/
gems:
  - jemoji
  - jekyll-sitemap
