# Site settings
title: David A Seeman
author: Dave Seeman
email: daveseeman12@gmail.com
description: Dave Seeman's blog
url: "http://daveas.me"
github: "http://daveas.github.io"
long_name:   daveaseeman
short_name:   daveas

# Build settings
markdown: kramdown
permalink: /:categories/:title
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
