# Site settings
title: Um, Dave?!
author: Dave Seeman
email: daveseeman12@gmail.com
description: Dave Seeman's blog.
url: "http://dseeman.github.io"
twitter_username:   dave_seeman
github_username:    dseeman
linkedin_username:  daveseeman

# Build settings
markdown: kramdown
permalink: /:categories/:title
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
